import Head from "next/head";

export default function CommunityOrganisations() {
  return (
    <>
      <main className="min-h-screen px-6 py-16 top-0 px-26 md:pt-18">
        <Head>
          <title>Data Governance Toolkit</title>
          <meta
            name="The Data Governance Toolkit is an online platform
          that helps community based organisations better manage and coordinate
          all of their data activities and data management in one place"
            content="Generated by create next app"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </main>
    </>
  );
}
